#!/bin/sh
if [ $# -eq 0 ]; then
    echo "Usage: `basename $0` \"<command>\""
    echo "Double quotes are optional, but if you plan to use | or && you'll need them"
    exit 65; # BADARGS
fi
while :; do clear; eval $@; sleep 1; done
